import CPOG.DynamicObservation

/-!
Greatest observation-respecting dynamic equivalence.

This module closes the existence/coarseness gap behind the paper's notation
≈^dyn_O.  It proves that bisimilarity generated by all observation-respecting
G/D/H bisimulations is itself an observation-respecting dynamic equivalence,
and that every other such dynamic equivalence refines it.
-/

namespace CPOG.GreatestDynamicObservation

open CPOG.ModalPreservation
open CPOG.SemanticProvenance
open CPOG.DynamicQuotient
open CPOG.DynamicObservation

universe uW uA uI

/-- A (not necessarily equivalence) G/D/H bisimulation on one model. -/
structure Bisimulation
    {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) where
  Z : W → W → Prop
  atom : ∀ {x y}, Z x y → ∀ a, M.val x a ↔ M.val y a

  forthG : ∀ {x y x'}, Z x y → M.G x x' →
    ∃ y', M.G y y' ∧ Z x' y'
  backG : ∀ {x y y'}, Z x y → M.G y y' →
    ∃ x', M.G x x' ∧ Z x' y'

  forthD : ∀ {x y x'}, Z x y → M.D x x' →
    ∃ y', M.D y y' ∧ Z x' y'
  backD : ∀ {x y y'}, Z x y → M.D y y' →
    ∃ x', M.D x x' ∧ Z x' y'

  forthH : ∀ {x y x'}, Z x y → M.H x x' →
    ∃ y', M.H y y' ∧ Z x' y'
  backH : ∀ {x y y'}, Z x y → M.H y y' →
    ∃ x', M.H x x' ∧ Z x' y'

/-- Identity is a bisimulation. -/
def identityBisimulation
    {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) : Bisimulation M where
  Z := Eq
  atom := by
    intro x y hxy a
    subst y
    rfl
  forthG := by
    intro x y x' hxy hstep
    subst y
    exact ⟨x', hstep, rfl⟩
  backG := by
    intro x y y' hxy hstep
    subst y
    exact ⟨y', hstep, rfl⟩
  forthD := by
    intro x y x' hxy hstep
    subst y
    exact ⟨x', hstep, rfl⟩
  backD := by
    intro x y y' hxy hstep
    subst y
    exact ⟨y', hstep, rfl⟩
  forthH := by
    intro x y x' hxy hstep
    subst y
    exact ⟨x', hstep, rfl⟩
  backH := by
    intro x y y' hxy hstep
    subst y
    exact ⟨y', hstep, rfl⟩

/-- Converse of a bisimulation is a bisimulation. -/
def converseBisimulation
    {W : Type uW} {Atom : Type uA} {M : Model W Atom}
    (B : Bisimulation M) : Bisimulation M where
  Z := fun x y => B.Z y x
  atom := by
    intro x y hxy a
    exact (B.atom hxy a).symm
  forthG := by
    intro x y x' hxy hxx'
    rcases B.backG hxy hxx' with ⟨y', hyy', hyx'⟩
    exact ⟨y', hyy', hyx'⟩
  backG := by
    intro x y y' hxy hyy'
    rcases B.forthG hxy hyy' with ⟨x', hxx', hy'x'⟩
    exact ⟨x', hxx', hy'x'⟩
  forthD := by
    intro x y x' hxy hxx'
    rcases B.backD hxy hxx' with ⟨y', hyy', hyx'⟩
    exact ⟨y', hyy', hyx'⟩
  backD := by
    intro x y y' hxy hyy'
    rcases B.forthD hxy hyy' with ⟨x', hxx', hy'x'⟩
    exact ⟨x', hxx', hy'x'⟩
  forthH := by
    intro x y x' hxy hxx'
    rcases B.backH hxy hxx' with ⟨y', hyy', hyx'⟩
    exact ⟨y', hyy', hyx'⟩
  backH := by
    intro x y y' hxy hyy'
    rcases B.forthH hxy hyy' with ⟨x', hxx', hy'x'⟩
    exact ⟨x', hxx', hy'x'⟩

/-- Relational composition of two bisimulations is again a bisimulation. -/
def composeBisimulation
    {W : Type uW} {Atom : Type uA} {M : Model W Atom}
    (B₁ B₂ : Bisimulation M) : Bisimulation M where
  Z := fun x z => ∃ y, B₁.Z x y ∧ B₂.Z y z
  atom := by
    intro x z hxz a
    rcases hxz with ⟨y, hxy, hyz⟩
    exact (B₁.atom hxy a).trans (B₂.atom hyz a)
  forthG := by
    intro x z x' hxz hxx'
    rcases hxz with ⟨y, hxy, hyz⟩
    rcases B₁.forthG hxy hxx' with ⟨y', hyy', hx'y'⟩
    rcases B₂.forthG hyz hyy' with ⟨z', hzz', hy'z'⟩
    exact ⟨z', hzz', ⟨y', hx'y', hy'z'⟩⟩
  backG := by
    intro x z z' hxz hzz'
    rcases hxz with ⟨y, hxy, hyz⟩
    rcases B₂.backG hyz hzz' with ⟨y', hyy', hy'z'⟩
    rcases B₁.backG hxy hyy' with ⟨x', hxx', hx'y'⟩
    exact ⟨x', hxx', ⟨y', hx'y', hy'z'⟩⟩
  forthD := by
    intro x z x' hxz hxx'
    rcases hxz with ⟨y, hxy, hyz⟩
    rcases B₁.forthD hxy hxx' with ⟨y', hyy', hx'y'⟩
    rcases B₂.forthD hyz hyy' with ⟨z', hzz', hy'z'⟩
    exact ⟨z', hzz', ⟨y', hx'y', hy'z'⟩⟩
  backD := by
    intro x z z' hxz hzz'
    rcases hxz with ⟨y, hxy, hyz⟩
    rcases B₂.backD hyz hzz' with ⟨y', hyy', hy'z'⟩
    rcases B₁.backD hxy hyy' with ⟨x', hxx', hx'y'⟩
    exact ⟨x', hxx', ⟨y', hx'y', hy'z'⟩⟩
  forthH := by
    intro x z x' hxz hxx'
    rcases hxz with ⟨y, hxy, hyz⟩
    rcases B₁.forthH hxy hxx' with ⟨y', hyy', hx'y'⟩
    rcases B₂.forthH hyz hyy' with ⟨z', hzz', hy'z'⟩
    exact ⟨z', hzz', ⟨y', hx'y', hy'z'⟩⟩
  backH := by
    intro x z z' hxz hzz'
    rcases hxz with ⟨y, hxy, hyz⟩
    rcases B₂.backH hyz hzz' with ⟨y', hyy', hy'z'⟩
    rcases B₁.backH hxy hyy' with ⟨x', hxx', hx'y'⟩
    exact ⟨x', hxx', ⟨y', hx'y', hy'z'⟩⟩

/-- Ordinary bisimilarity: some bisimulation relates the pair. -/
def Bisimilar
    {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (x y : W) : Prop :=
  ∃ B : Bisimulation M, B.Z x y

theorem bisimilar_refl
    {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (x : W) :
    Bisimilar M x x :=
  ⟨identityBisimulation M, rfl⟩

theorem bisimilar_symm
    {W : Type uW} {Atom : Type uA} {M : Model W Atom}
    {x y : W} (hxy : Bisimilar M x y) :
    Bisimilar M y x := by
  rcases hxy with ⟨B, hB⟩
  exact ⟨converseBisimulation B, hB⟩

theorem bisimilar_trans
    {W : Type uW} {Atom : Type uA} {M : Model W Atom}
    {x y z : W}
    (hxy : Bisimilar M x y) (hyz : Bisimilar M y z) :
    Bisimilar M x z := by
  rcases hxy with ⟨B₁, h₁⟩
  rcases hyz with ⟨B₂, h₂⟩
  exact ⟨composeBisimulation B₁ B₂, ⟨y, h₁, h₂⟩⟩

theorem bisimilar_equivalence
    {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) :
    Equivalence (Bisimilar M) :=
  ⟨bisimilar_refl M, bisimilar_symm, bisimilar_trans⟩

/-- Bisimilarity itself satisfies the bisimulation clauses. -/
def greatestBisimulation
    {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) : Bisimulation M where
  Z := Bisimilar M
  atom := by
    intro x y hxy a
    rcases hxy with ⟨B, hB⟩
    exact B.atom hB a
  forthG := by
    intro x y x' hxy hxx'
    rcases hxy with ⟨B, hB⟩
    rcases B.forthG hB hxx' with ⟨y', hyy', hrel⟩
    exact ⟨y', hyy', ⟨B, hrel⟩⟩
  backG := by
    intro x y y' hxy hyy'
    rcases hxy with ⟨B, hB⟩
    rcases B.backG hB hyy' with ⟨x', hxx', hrel⟩
    exact ⟨x', hxx', ⟨B, hrel⟩⟩
  forthD := by
    intro x y x' hxy hxx'
    rcases hxy with ⟨B, hB⟩
    rcases B.forthD hB hxx' with ⟨y', hyy', hrel⟩
    exact ⟨y', hyy', ⟨B, hrel⟩⟩
  backD := by
    intro x y y' hxy hyy'
    rcases hxy with ⟨B, hB⟩
    rcases B.backD hB hyy' with ⟨x', hxx', hrel⟩
    exact ⟨x', hxx', ⟨B, hrel⟩⟩
  forthH := by
    intro x y x' hxy hxx'
    rcases hxy with ⟨B, hB⟩
    rcases B.forthH hB hxx' with ⟨y', hyy', hrel⟩
    exact ⟨y', hyy', ⟨B, hrel⟩⟩
  backH := by
    intro x y y' hxy hyy'
    rcases hxy with ⟨B, hB⟩
    rcases B.backH hB hyy' with ⟨x', hxx', hrel⟩
    exact ⟨x', hxx', ⟨B, hrel⟩⟩

/-- A bisimulation additionally constrained to preserve the selected observations. -/
structure ObservationBisimulation
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) where
  bisim : Bisimulation M
  observation : ∀ {x y}, bisim.Z x y → ObsEq O x y

def identityObservationBisimulation
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) :
    ObservationBisimulation M O where
  bisim := identityBisimulation M
  observation := by
    intro x y hxy
    subst y
    exact obsEq_refl O x

def converseObservationBisimulation
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    (B : ObservationBisimulation M O) :
    ObservationBisimulation M O where
  bisim := converseBisimulation B.bisim
  observation := by
    intro x y hxy
    exact obsEq_symm (B.observation hxy)

def composeObservationBisimulation
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    (B₁ B₂ : ObservationBisimulation M O) :
    ObservationBisimulation M O where
  bisim := composeBisimulation B₁.bisim B₂.bisim
  observation := by
    intro x z hxz
    rcases hxz with ⟨y, hxy, hyz⟩
    exact obsEq_trans (B₁.observation hxy) (B₂.observation hyz)

/-- The union, in existential form, of all observation-respecting bisimulations. -/
def ObsBisimilar
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W)
    (x y : W) : Prop :=
  ∃ B : ObservationBisimulation M O, B.bisim.Z x y

theorem obsBisimilar_refl
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) (x : W) :
    ObsBisimilar M O x x :=
  ⟨identityObservationBisimulation M O, rfl⟩

theorem obsBisimilar_symm
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    {x y : W} (hxy : ObsBisimilar M O x y) :
    ObsBisimilar M O y x := by
  rcases hxy with ⟨B, hB⟩
  exact ⟨converseObservationBisimulation B, hB⟩

theorem obsBisimilar_trans
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    {x y z : W}
    (hxy : ObsBisimilar M O x y)
    (hyz : ObsBisimilar M O y z) :
    ObsBisimilar M O x z := by
  rcases hxy with ⟨B₁, h₁⟩
  rcases hyz with ⟨B₂, h₂⟩
  exact ⟨composeObservationBisimulation B₁ B₂, ⟨y, h₁, h₂⟩⟩

theorem obsBisimilar_equivalence
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) :
    Equivalence (ObsBisimilar M O) :=
  ⟨obsBisimilar_refl M O, obsBisimilar_symm, obsBisimilar_trans⟩

def greatestObservationBisimulation
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) :
    ObservationBisimulation M O where
  bisim :=
    { Z := ObsBisimilar M O
      atom := by
        intro x y hxy a
        rcases hxy with ⟨B, hB⟩
        exact B.bisim.atom hB a
      forthG := by
        intro x y x' hxy hxx'
        rcases hxy with ⟨B, hB⟩
        rcases B.bisim.forthG hB hxx' with ⟨y', hyy', hrel⟩
        exact ⟨y', hyy', ⟨B, hrel⟩⟩
      backG := by
        intro x y y' hxy hyy'
        rcases hxy with ⟨B, hB⟩
        rcases B.bisim.backG hB hyy' with ⟨x', hxx', hrel⟩
        exact ⟨x', hxx', ⟨B, hrel⟩⟩
      forthD := by
        intro x y x' hxy hxx'
        rcases hxy with ⟨B, hB⟩
        rcases B.bisim.forthD hB hxx' with ⟨y', hyy', hrel⟩
        exact ⟨y', hyy', ⟨B, hrel⟩⟩
      backD := by
        intro x y y' hxy hyy'
        rcases hxy with ⟨B, hB⟩
        rcases B.bisim.backD hB hyy' with ⟨x', hxx', hrel⟩
        exact ⟨x', hxx', ⟨B, hrel⟩⟩
      forthH := by
        intro x y x' hxy hxx'
        rcases hxy with ⟨B, hB⟩
        rcases B.bisim.forthH hB hxx' with ⟨y', hyy', hrel⟩
        exact ⟨y', hyy', ⟨B, hrel⟩⟩
      backH := by
        intro x y y' hxy hyy'
        rcases hxy with ⟨B, hB⟩
        rcases B.bisim.backH hB hyy' with ⟨x', hxx', hrel⟩
        exact ⟨x', hxx', ⟨B, hrel⟩⟩ }
  observation := by
    intro x y hxy
    rcases hxy with ⟨B, hB⟩
    exact B.observation hB

/-- The greatest observation-respecting relation is an actual DynamicEquivalence. -/
def greatestObservationDynamicEquivalence
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) :
    ObservationDynamicEquivalence M O where
  dyn :=
    { E := ObsBisimilar M O
      equiv := obsBisimilar_equivalence M O
      atom := (greatestObservationBisimulation M O).bisim.atom
      forthG := (greatestObservationBisimulation M O).bisim.forthG
      backG := (greatestObservationBisimulation M O).bisim.backG
      forthD := (greatestObservationBisimulation M O).bisim.forthD
      backD := (greatestObservationBisimulation M O).bisim.backD
      forthH := (greatestObservationBisimulation M O).bisim.forthH
      backH := (greatestObservationBisimulation M O).bisim.backH }
  respectsObservation := (greatestObservationBisimulation M O).observation

/-- Convert any existing observation-safe DynamicEquivalence to an observation bisimulation. -/
def asObservationBisimulation
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    (B : ObservationDynamicEquivalence M O) :
    ObservationBisimulation M O where
  bisim :=
    { Z := B.dyn.E
      atom := B.dyn.atom
      forthG := B.dyn.forthG
      backG := B.dyn.backG
      forthD := B.dyn.forthD
      backD := B.dyn.backD
      forthH := B.dyn.forthH
      backH := B.dyn.backH }
  observation := B.respectsObservation

/--
Greatestness: every observation-respecting DynamicEquivalence is contained in
the canonical relation ObsBisimilar.
-/
theorem every_dynamic_observation_equivalence_refines_greatest
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    (B : ObservationDynamicEquivalence M O)
    {x y : W}
    (hxy : B.dyn.E x y) :
    (greatestObservationDynamicEquivalence M O).dyn.E x y :=
  ⟨asObservationBisimulation B, hxy⟩

/--
Coarsest-quotient form: every equality produced by any safe dynamic quotient is
also an equality in the canonical greatest dynamic observation quotient.
-/
theorem greatest_dynamic_observation_quotient_is_coarsest
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    {M : Model W Atom} {O : ObservationSystem ι W}
    (B : ObservationDynamicEquivalence M O)
    {x y : W}
    (hxy : CPOG.DynamicQuotient.quotientMap B.dyn x =
      CPOG.DynamicQuotient.quotientMap B.dyn y) :
    CPOG.DynamicQuotient.quotientMap
        (greatestObservationDynamicEquivalence M O).dyn x =
      CPOG.DynamicQuotient.quotientMap
        (greatestObservationDynamicEquivalence M O).dyn y := by
  apply (CPOG.DynamicQuotient.quotientMap_eq_iff
    (greatestObservationDynamicEquivalence M O).dyn x y).2
  apply every_dynamic_observation_equivalence_refines_greatest B
  exact (CPOG.DynamicQuotient.quotientMap_eq_iff B.dyn x y).1 hxy

/--
The canonical greatest quotient simultaneously refines the static observation
quotient and preserves every formula of the tri-modal G/D/H language.
-/
theorem greatest_dynamic_observation_quotient_is_safe
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W) :
    (∀ {x y : W},
      CPOG.DynamicQuotient.quotientMap
        (greatestObservationDynamicEquivalence M O).dyn x =
      CPOG.DynamicQuotient.quotientMap
        (greatestObservationDynamicEquivalence M O).dyn y →
      ObsEq O x y) ∧
    (∀ (phi : Formula Atom) (w : W),
      Sat M w phi ↔
        Sat (CPOG.DynamicQuotient.quotientModel
          (greatestObservationDynamicEquivalence M O).dyn)
          (CPOG.DynamicQuotient.quotientMap
            (greatestObservationDynamicEquivalence M O).dyn w) phi) := by
  exact dynamic_observation_quotient_is_semantically_safe
    (greatestObservationDynamicEquivalence M O)


/--
Paper Theorem 2B specialized to the canonical coarsest dynamic observation
quotient.  If the selected observations determine the persistent FirstCommit
label, distinct FirstCommit branches still refute .2 after taking the greatest
safe quotient.
-/
theorem firstCommit_dotTwo_fails_on_greatest_observation_quotient
    {ι : Type uI} {W : Type uW} {Atom : Type uA}
    (M : Model W Atom) (O : ObservationSystem ι W)
    {C : Type}
    (first : W -> Option C)
    (root a b : W) (ca cb : C)
    (hc : ca ≠ cb)
    (hrootA : M.G root a) (hrootB : M.G root b)
    (hfirstA : first a = some ca) (hfirstB : first b = some cb)
    (hpersist : forall {x y : W} {c : C},
      M.G x y -> first x = some c -> first y = some c)
    (hobservesFirst : forall {x y : W}, ObsEq O x y -> first x = first y) :
    Not (CPOG.EpistemicPotentialism.DotTwoR
      (CPOG.EpistemicPotentialism.AbstractRel M.G
        (CPOG.DynamicQuotient.quotientMap
          (greatestObservationDynamicEquivalence M O).dyn))
      (CPOG.EpistemicPotentialism.AbstractFirstCommit
        (CPOG.DynamicQuotient.quotientMap
          (greatestObservationDynamicEquivalence M O).dyn)
        first ca)
      (CPOG.DynamicQuotient.quotientMap
        (greatestObservationDynamicEquivalence M O).dyn root)) := by
  apply CPOG.DynamicQuotient.firstCommit_dotTwo_fails_on_dynamicQuotient
    (B := (greatestObservationDynamicEquivalence M O).dyn)
    first root a b ca cb hc hrootA hrootB hfirstA hfirstB hpersist
  intro x y hxy
  exact hobservesFirst
    ((greatestObservationDynamicEquivalence M O).respectsObservation hxy)

end CPOG.GreatestDynamicObservation
